### ISSUE TITLE
conda and jupyter commands not found

### ISSUE THREAD

**Issue by romeokienzler** [mit-satori/getting-started#9]
tried to create a jupyter env using an interactive batch job but the commands are not found (e.g. documentation inconsistent?)

=> https://mit-satori.github.io/satori-ssh.html

I did the following
1. login: ssh -L 10001:node0047.inband:10001 romeok@satori-login-001.mit.edu
2. bsub -W 0:15 -q interactive -gpu "num=1" -R "select[type==any]" -Ip bash
>> Job <6457> is submitted to queue <interactive>.
>> <<Waiting for dispatch ...>>
>> <<Starting on node0047.inband>>
3. I get conda: command not found on node0047.inband and on satori-login-001.mit.edu
4. I get  jupyter: command not found on node0047.inband and on satori-login-001.mit.edu

**Comment by johncohn** [comment]
It sounds like you didn't do the steps to install wmlce 
https://mit-satori.github.io/satori-ai-frameworks.html#


John Cohn Ph.D, 
IBM Fellow , MIT-IBM Watson AI Lab
phone 802-578-0985

**Comment by romeokienzler** [comment]
this is correct, there was a hint missing (for me) to have a look at that page, but since all other didn't seem to need that hint I won't create a PR
